# name: upload website

# on:
#   push:
#     branches:
#       - "main"

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: jakejarvis/s3-sync-action@master